server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_study_202210_02  #db? ?? ??? ???? ????
          #mysql:// < 이거 조심 mysql// 이렇게들 많이 씀
    username: root
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml